### ISSUE TITLE
ModuleNotFoundError: No module named 'baselines'

### ISSUE THREAD

**Issue by ghost** [XinZhang525/cGAIL#1]
@XinZhang525 
i downloaded `expert_traj` and placed it inside cGail root directory,
when running cGail i get an error:
```
(d2) home@home-lnx:~/programs/cGAIL-master$ python main.py --cgail --D-lr 1e-3 --num-process 1
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from a2c_ppo_acktr import algo, utils
  File "/home/home/programs/cGAIL-master/a2c_ppo_acktr/algo/__init__.py", line 1, in <module>
    from .a2c_acktr import A2C_ACKTR
  File "/home/home/programs/cGAIL-master/a2c_ppo_acktr/algo/a2c_acktr.py", line 5, in <module>
    from a2c_ppo_acktr.algo.kfac import KFACOptimizer
  File "/home/home/programs/cGAIL-master/a2c_ppo_acktr/algo/kfac.py", line 8, in <module>
    from a2c_ppo_acktr.utils import AddBias
  File "/home/home/programs/cGAIL-master/a2c_ppo_acktr/utils.py", line 7, in <module>
    from a2c_ppo_acktr.envs import VecNormalize
  File "/home/home/programs/cGAIL-master/a2c_ppo_acktr/envs.py", line 7, in <module>
    from baselines import bench
ModuleNotFoundError: No module named 'baselines'
```

**Comment by ghost** [comment]
ok i installed baseline, now it's working
